### ISSUE TITLE
[Feat] 나만의 플리 폰트 설정하기

### ISSUE THREAD

**Issue by iDrogba** [TwoInterval/Mapli#49]
### 구현해야하는 요소들
- 폰트 설정 기능
- 템플릿 enum타입 생성

### 구현 방안
- 그냥해~
 
### TODO
- [x] 템플릿 enum타입으로 변환
- [x] 폰트 찾아서 설정하기

### 비고 및 한계
- 디자이너께 컨펌받아야함

**Comment by lau0505** [comment]
디자이너께 컨펌ㅋㅋㅋㅋㅋㅋㅋㅋ한번에 통과되도록 잘 찾아보세여 찡-긋-!😉
